log_level = "debug"

[server]
tokens = ["xxyxx"]
cert_file = ".direnv/localhost/cert.pem"
key_file = ".direnv/localhost/key.pem"

[client]
token = "xxyxx"
server_cas = ".direnv/localhost/cert.pem"

[client.destinations.sws]
addr = ":8081"

[client.sources.sws]
addr = ":9999"
