log_level = "debug"

[server]
tokens = ["xxyxx"]
cert_file = ".direnv/localhost/cert.pem"
key_file = ".direnv/localhost/key.pem"

[client]
token = "xxyxx"
server_addr = "127.0.0.1:19190"
server_cert_file = ".direnv/localhost/cert.pem"

[client.direct]
bind_addr = ":19192"
cert_file = ".direnv/localhost/cert.pem"
key_file = ".direnv/localhost/key.pem"

[client.destinations.sws]
addr = ":8081"

[client.sources.sws]
addr = ":9999"
