version: "0.5"

processes:
  build:
    command: make
  certs:
    command: gen-local-certs
  server:
    command: connet-server -debug -auth xxyxx -server-cert .direnv/localhost/cert.pem -server-key .direnv/localhost/key.pem
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
  client-listen:
    command: connet -debug -auth xxyxx -destination-name sws -destination-addr ":8081" -ca-cert .direnv/minica.pem -ca-key .direnv/minica-key.pem
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
      server:
        condition: process_started
  client-serve:
    command: connet -debug -auth xxyxx -direct-addr ":19193" -source-name sws -source-addr ":9999" -ca-cert .direnv/minica.pem -ca-key .direnv/minica-key.pem
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
      server:
        condition: process_started
      client-listen:
        condition: process_started
  upstream:
    command: static-web-server --port 8081 --root . --directory-listing
