version: "0.5"

processes:
  build:
    command: make
    availability:
      restart: "exit_on_failure"
  certs:
    command: gen-local-certs
  server:
    command: connet server --config examples/minimal.toml
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
  client-dst:
    command: connet --config examples/client-destination.toml
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
      server:
        condition: process_started
  client-src:
    command: connet --config examples/client-source.toml
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
      server:
        condition: process_started
      client-dst:
        condition: process_started
