version: "0.5"

processes:
  server:
    command: connet-server -debug
  client:
    command: connet -debug -auth abc -listen-name sws -listen-target ":9999" -connect-name sws -connect-source ":9998"
  upstream:
    command: static-web-server --port 9999 --root . --directory-listing
