version: "0.5"

processes:
  certs:
    command: gen-local-certs
  server:
    command: connet-server -debug -auth xxyxx -server-cert .direnv/localhost/cert.pem -server-key .direnv/localhost/key.pem
    depends_on:
      certs:
        condition: process_completed
  client:
    command: connet -debug -auth xxyxx -listen-name sws -listen-target ":9999" -connect-name sws -connect-source ":9998" -ca-cert .direnv/minica.pem -ca-key .direnv/minica-key.pem
    depends_on:
      certs:
        condition: process_completed
  upstream:
    command: static-web-server --port 9999 --root . --directory-listing
