version: "0.5"

processes:
  build:
    command: make
    availability:
      restart: "exit_on_failure"
  certs:
    command: gen-local-certs
  server:
    command: connet server examples/minimal.toml
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
  client-listen:
    command: connet client examples/client-destination.toml
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
      server:
        condition: process_started
  client-serve:
    command: connet client examples/client-source.toml
    depends_on:
      build:
        condition: process_completed_successfully
      certs:
        condition: process_completed
      server:
        condition: process_started
      client-listen:
        condition: process_started
  upstream:
    command: static-web-server --port 8081 --root . --directory-listing
