// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: client.proto

package pbclient

import (
	pberror "github.com/connet-dev/connet/proto/pberror"
	pbmodel "github.com/connet-dev/connet/proto/pbmodel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ReconnectToken []byte                 `protobuf:"bytes,2,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	BuildVersion   string                 `protobuf:"bytes,3,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	Metadata       string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateReq) GetReconnectToken() []byte {
	if x != nil {
		return x.ReconnectToken
	}
	return nil
}

func (x *AuthenticateReq) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *AuthenticateReq) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type AuthenticateResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Error          *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Public         *pbmodel.AddrPort      `protobuf:"bytes,2,opt,name=public,proto3" json:"public,omitempty"`
	ReconnectToken []byte                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticateResp) Reset() {
	*x = AuthenticateResp{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResp) ProtoMessage() {}

func (x *AuthenticateResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResp.ProtoReflect.Descriptor instead.
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResp) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AuthenticateResp) GetPublic() *pbmodel.AddrPort {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *AuthenticateResp) GetReconnectToken() []byte {
	if x != nil {
		return x.ReconnectToken
	}
	return nil
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Soft one-of
	Announce      *Request_Announce `protobuf:"bytes,1,opt,name=announce,proto3" json:"announce,omitempty"`
	Relay         *Request_Relay    `protobuf:"bytes,2,opt,name=relay,proto3" json:"relay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetAnnounce() *Request_Announce {
	if x != nil {
		return x.Announce
	}
	return nil
}

func (x *Request) GetRelay() *Request_Relay {
	if x != nil {
		return x.Relay
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Soft one-of if error is nil
	Announce      *Response_Announce `protobuf:"bytes,2,opt,name=announce,proto3" json:"announce,omitempty"`
	Relay         *Response_Relays   `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetAnnounce() *Response_Announce {
	if x != nil {
		return x.Announce
	}
	return nil
}

func (x *Response) GetRelay() *Response_Relays {
	if x != nil {
		return x.Relay
	}
	return nil
}

type Peer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Directs           []*pbmodel.AddrPort    `protobuf:"bytes,3,rep,name=directs,proto3" json:"directs,omitempty"`
	RelayIds          []string               `protobuf:"bytes,6,rep,name=relay_ids,json=relayIds,proto3" json:"relay_ids,omitempty"`
	ServerCertificate []byte                 `protobuf:"bytes,4,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"` // certificate to use when connecting to this client
	ClientCertificate []byte                 `protobuf:"bytes,5,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"` // certificate that this client uses when connecting
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *Peer) GetDirects() []*pbmodel.AddrPort {
	if x != nil {
		return x.Directs
	}
	return nil
}

func (x *Peer) GetRelayIds() []string {
	if x != nil {
		return x.RelayIds
	}
	return nil
}

func (x *Peer) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

func (x *Peer) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

type RemotePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // peer id as assigned by the control server
	Metadata      string                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,8,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePeer) Reset() {
	*x = RemotePeer{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePeer) ProtoMessage() {}

func (x *RemotePeer) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePeer.ProtoReflect.Descriptor instead.
func (*RemotePeer) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *RemotePeer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemotePeer) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *RemotePeer) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type Relay struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Addresses         []*pbmodel.HostPort    `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ServerCertificate []byte                 `protobuf:"bytes,2,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"` // endpoint specific certificate to be used by the client
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Relay) Reset() {
	*x = Relay{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relay) ProtoMessage() {}

func (x *Relay) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relay.ProtoReflect.Descriptor instead.
func (*Relay) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *Relay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Relay) GetAddresses() []*pbmodel.HostPort {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Relay) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

type DirectRelay struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // relay id as assigned by the control server
	Addresses               []*pbmodel.HostPort    `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ServerCertificate       []byte                 `protobuf:"bytes,3,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`                   // generic certificate used by this relay
	AuthenticationSignature []byte                 `protobuf:"bytes,4,opt,name=authentication_signature,json=authenticationSignature,proto3" json:"authentication_signature,omitempty"` // endpoint/role specific signature to use at the relay
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DirectRelay) Reset() {
	*x = DirectRelay{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRelay) ProtoMessage() {}

func (x *DirectRelay) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRelay.ProtoReflect.Descriptor instead.
func (*DirectRelay) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *DirectRelay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DirectRelay) GetAddresses() []*pbmodel.HostPort {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *DirectRelay) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

func (x *DirectRelay) GetAuthenticationSignature() []byte {
	if x != nil {
		return x.AuthenticationSignature
	}
	return nil
}

type Request_Announce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *pbmodel.Endpoint      `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Role          pbmodel.Role           `protobuf:"varint,2,opt,name=role,proto3,enum=model.Role" json:"role,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_Announce) Reset() {
	*x = Request_Announce{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Announce) ProtoMessage() {}

func (x *Request_Announce) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Announce.ProtoReflect.Descriptor instead.
func (*Request_Announce) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Request_Announce) GetEndpoint() *pbmodel.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Request_Announce) GetRole() pbmodel.Role {
	if x != nil {
		return x.Role
	}
	return pbmodel.Role(0)
}

func (x *Request_Announce) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type Request_Relay struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Endpoint          *pbmodel.Endpoint      `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Role              pbmodel.Role           `protobuf:"varint,2,opt,name=role,proto3,enum=model.Role" json:"role,omitempty"`
	ClientCertificate []byte                 `protobuf:"bytes,3,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"` // certificate to use when connecting to a relay
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Request_Relay) Reset() {
	*x = Request_Relay{}
	mi := &file_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Relay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Relay) ProtoMessage() {}

func (x *Request_Relay) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Relay.ProtoReflect.Descriptor instead.
func (*Request_Relay) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Request_Relay) GetEndpoint() *pbmodel.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Request_Relay) GetRole() pbmodel.Role {
	if x != nil {
		return x.Role
	}
	return pbmodel.Role(0)
}

func (x *Request_Relay) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

type Response_Announce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*RemotePeer          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_Announce) Reset() {
	*x = Response_Announce{}
	mi := &file_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Announce) ProtoMessage() {}

func (x *Response_Announce) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Announce.ProtoReflect.Descriptor instead.
func (*Response_Announce) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Response_Announce) GetPeers() []*RemotePeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Response_Relays struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relays        []*Relay               `protobuf:"bytes,1,rep,name=relays,proto3" json:"relays,omitempty"`
	Directs       []*DirectRelay         `protobuf:"bytes,2,rep,name=directs,proto3" json:"directs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_Relays) Reset() {
	*x = Response_Relays{}
	mi := &file_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_Relays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Relays) ProtoMessage() {}

func (x *Response_Relays) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Relays.ProtoReflect.Descriptor instead.
func (*Response_Relays) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Response_Relays) GetRelays() []*Relay {
	if x != nil {
		return x.Relays
	}
	return nil
}

func (x *Response_Relays) GetDirects() []*DirectRelay {
	if x != nil {
		return x.Directs
	}
	return nil
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x06client\x1a\verror.proto\x1a\vmodel.proto\"\x91\x01\n" +
	"\x0fAuthenticateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x0freconnect_token\x18\x02 \x01(\fR\x0ereconnectToken\x12#\n" +
	"\rbuild_version\x18\x03 \x01(\tR\fbuildVersion\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"\x88\x01\n" +
	"\x10AuthenticateResp\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\x12'\n" +
	"\x06public\x18\x02 \x01(\v2\x0f.model.AddrPortR\x06public\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\fR\x0ereconnectToken\"\xef\x02\n" +
	"\aRequest\x124\n" +
	"\bannounce\x18\x01 \x01(\v2\x18.client.Request.AnnounceR\bannounce\x12+\n" +
	"\x05relay\x18\x02 \x01(\v2\x15.client.Request.RelayR\x05relay\x1az\n" +
	"\bAnnounce\x12+\n" +
	"\bendpoint\x18\x01 \x01(\v2\x0f.model.EndpointR\bendpoint\x12\x1f\n" +
	"\x04role\x18\x02 \x01(\x0e2\v.model.RoleR\x04role\x12 \n" +
	"\x04peer\x18\x03 \x01(\v2\f.client.PeerR\x04peer\x1a\x84\x01\n" +
	"\x05Relay\x12+\n" +
	"\bendpoint\x18\x01 \x01(\v2\x0f.model.EndpointR\bendpoint\x12\x1f\n" +
	"\x04role\x18\x02 \x01(\x0e2\v.model.RoleR\x04role\x12-\n" +
	"\x12client_certificate\x18\x03 \x01(\fR\x11clientCertificate\"\xaa\x02\n" +
	"\bResponse\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\x125\n" +
	"\bannounce\x18\x02 \x01(\v2\x19.client.Response.AnnounceR\bannounce\x12-\n" +
	"\x05relay\x18\x03 \x01(\v2\x17.client.Response.RelaysR\x05relay\x1a4\n" +
	"\bAnnounce\x12(\n" +
	"\x05peers\x18\x01 \x03(\v2\x12.client.RemotePeerR\x05peers\x1a^\n" +
	"\x06Relays\x12%\n" +
	"\x06relays\x18\x01 \x03(\v2\r.client.RelayR\x06relays\x12-\n" +
	"\adirects\x18\x02 \x03(\v2\x13.client.DirectRelayR\adirects\"\xac\x01\n" +
	"\x04Peer\x12)\n" +
	"\adirects\x18\x03 \x03(\v2\x0f.model.AddrPortR\adirects\x12\x1b\n" +
	"\trelay_ids\x18\x06 \x03(\tR\brelayIds\x12-\n" +
	"\x12server_certificate\x18\x04 \x01(\fR\x11serverCertificate\x12-\n" +
	"\x12client_certificate\x18\x05 \x01(\fR\x11clientCertificate\"Z\n" +
	"\n" +
	"RemotePeer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\tR\bmetadata\x12 \n" +
	"\x04peer\x18\b \x01(\v2\f.client.PeerR\x04peer\"u\n" +
	"\x05Relay\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12-\n" +
	"\taddresses\x18\x04 \x03(\v2\x0f.model.HostPortR\taddresses\x12-\n" +
	"\x12server_certificate\x18\x02 \x01(\fR\x11serverCertificate\"\xb6\x01\n" +
	"\vDirectRelay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\taddresses\x18\x02 \x03(\v2\x0f.model.HostPortR\taddresses\x12-\n" +
	"\x12server_certificate\x18\x03 \x01(\fR\x11serverCertificate\x129\n" +
	"\x18authentication_signature\x18\x04 \x01(\fR\x17authenticationSignatureB-Z+github.com/connet-dev/connet/proto/pbclientb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_client_proto_goTypes = []any{
	(*AuthenticateReq)(nil),   // 0: client.AuthenticateReq
	(*AuthenticateResp)(nil),  // 1: client.AuthenticateResp
	(*Request)(nil),           // 2: client.Request
	(*Response)(nil),          // 3: client.Response
	(*Peer)(nil),              // 4: client.Peer
	(*RemotePeer)(nil),        // 5: client.RemotePeer
	(*Relay)(nil),             // 6: client.Relay
	(*DirectRelay)(nil),       // 7: client.DirectRelay
	(*Request_Announce)(nil),  // 8: client.Request.Announce
	(*Request_Relay)(nil),     // 9: client.Request.Relay
	(*Response_Announce)(nil), // 10: client.Response.Announce
	(*Response_Relays)(nil),   // 11: client.Response.Relays
	(*pberror.Error)(nil),     // 12: error.Error
	(*pbmodel.AddrPort)(nil),  // 13: model.AddrPort
	(*pbmodel.HostPort)(nil),  // 14: model.HostPort
	(*pbmodel.Endpoint)(nil),  // 15: model.Endpoint
	(pbmodel.Role)(0),         // 16: model.Role
}
var file_client_proto_depIdxs = []int32{
	12, // 0: client.AuthenticateResp.error:type_name -> error.Error
	13, // 1: client.AuthenticateResp.public:type_name -> model.AddrPort
	8,  // 2: client.Request.announce:type_name -> client.Request.Announce
	9,  // 3: client.Request.relay:type_name -> client.Request.Relay
	12, // 4: client.Response.error:type_name -> error.Error
	10, // 5: client.Response.announce:type_name -> client.Response.Announce
	11, // 6: client.Response.relay:type_name -> client.Response.Relays
	13, // 7: client.Peer.directs:type_name -> model.AddrPort
	4,  // 8: client.RemotePeer.peer:type_name -> client.Peer
	14, // 9: client.Relay.addresses:type_name -> model.HostPort
	14, // 10: client.DirectRelay.addresses:type_name -> model.HostPort
	15, // 11: client.Request.Announce.endpoint:type_name -> model.Endpoint
	16, // 12: client.Request.Announce.role:type_name -> model.Role
	4,  // 13: client.Request.Announce.peer:type_name -> client.Peer
	15, // 14: client.Request.Relay.endpoint:type_name -> model.Endpoint
	16, // 15: client.Request.Relay.role:type_name -> model.Role
	5,  // 16: client.Response.Announce.peers:type_name -> client.RemotePeer
	6,  // 17: client.Response.Relays.relays:type_name -> client.Relay
	7,  // 18: client.Response.Relays.directs:type_name -> client.DirectRelay
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
