// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: relay.proto

package pbrelay

import (
	pberror "github.com/connet-dev/connet/proto/pberror"
	pbmodel "github.com/connet-dev/connet/proto/pbmodel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateReq struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Token                  string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Addresses              []*pbmodel.HostPort    `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ReconnectToken         []byte                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	BuildVersion           string                 `protobuf:"bytes,4,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	Metadata               string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ServerCertificate      []byte                 `protobuf:"bytes,7,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	RelayAuthenticationKey []byte                 `protobuf:"bytes,8,opt,name=relay_authentication_key,json=relayAuthenticationKey,proto3" json:"relay_authentication_key,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateReq) GetAddresses() []*pbmodel.HostPort {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *AuthenticateReq) GetReconnectToken() []byte {
	if x != nil {
		return x.ReconnectToken
	}
	return nil
}

func (x *AuthenticateReq) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *AuthenticateReq) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AuthenticateReq) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

func (x *AuthenticateReq) GetRelayAuthenticationKey() []byte {
	if x != nil {
		return x.RelayAuthenticationKey
	}
	return nil
}

type AuthenticateResp struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Error                    *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ControlId                string                 `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	ReconnectToken           []byte                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	ControlAuthenticationKey []byte                 `protobuf:"bytes,4,opt,name=control_authentication_key,json=controlAuthenticationKey,proto3" json:"control_authentication_key,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AuthenticateResp) Reset() {
	*x = AuthenticateResp{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResp) ProtoMessage() {}

func (x *AuthenticateResp) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResp.ProtoReflect.Descriptor instead.
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResp) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AuthenticateResp) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *AuthenticateResp) GetReconnectToken() []byte {
	if x != nil {
		return x.ReconnectToken
	}
	return nil
}

func (x *AuthenticateResp) GetControlAuthenticationKey() []byte {
	if x != nil {
		return x.ControlAuthenticationKey
	}
	return nil
}

type ClientAuthentication struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Endpoint       *pbmodel.Endpoint      `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Role           pbmodel.Role           `protobuf:"varint,2,opt,name=role,proto3,enum=model.Role" json:"role,omitempty"`
	CertificateKey string                 `protobuf:"bytes,3,opt,name=certificate_key,json=certificateKey,proto3" json:"certificate_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientAuthentication) Reset() {
	*x = ClientAuthentication{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthentication) ProtoMessage() {}

func (x *ClientAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthentication.ProtoReflect.Descriptor instead.
func (*ClientAuthentication) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ClientAuthentication) GetEndpoint() *pbmodel.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ClientAuthentication) GetRole() pbmodel.Role {
	if x != nil {
		return x.Role
	}
	return pbmodel.Role(0)
}

func (x *ClientAuthentication) GetCertificateKey() string {
	if x != nil {
		return x.CertificateKey
	}
	return ""
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\x05relay\x1a\verror.proto\x1a\vmodel.proto\"\xa9\x02\n" +
	"\x0fAuthenticateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12-\n" +
	"\taddresses\x18\x05 \x03(\v2\x0f.model.HostPortR\taddresses\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\fR\x0ereconnectToken\x12#\n" +
	"\rbuild_version\x18\x04 \x01(\tR\fbuildVersion\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12-\n" +
	"\x12server_certificate\x18\a \x01(\fR\x11serverCertificate\x128\n" +
	"\x18relay_authentication_key\x18\b \x01(\fR\x16relayAuthenticationKey\"\xbc\x01\n" +
	"\x10AuthenticateResp\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tR\tcontrolId\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\fR\x0ereconnectToken\x12<\n" +
	"\x1acontrol_authentication_key\x18\x04 \x01(\fR\x18controlAuthenticationKey\"\x8d\x01\n" +
	"\x14ClientAuthentication\x12+\n" +
	"\bendpoint\x18\x01 \x01(\v2\x0f.model.EndpointR\bendpoint\x12\x1f\n" +
	"\x04role\x18\x02 \x01(\x0e2\v.model.RoleR\x04role\x12'\n" +
	"\x0fcertificate_key\x18\x03 \x01(\tR\x0ecertificateKeyB,Z*github.com/connet-dev/connet/proto/pbrelayb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relay_proto_goTypes = []any{
	(*AuthenticateReq)(nil),      // 0: relay.AuthenticateReq
	(*AuthenticateResp)(nil),     // 1: relay.AuthenticateResp
	(*ClientAuthentication)(nil), // 2: relay.ClientAuthentication
	(*pbmodel.HostPort)(nil),     // 3: model.HostPort
	(*pberror.Error)(nil),        // 4: error.Error
	(*pbmodel.Endpoint)(nil),     // 5: model.Endpoint
	(pbmodel.Role)(0),            // 6: model.Role
}
var file_relay_proto_depIdxs = []int32{
	3, // 0: relay.AuthenticateReq.addresses:type_name -> model.HostPort
	4, // 1: relay.AuthenticateResp.error:type_name -> error.Error
	5, // 2: relay.ClientAuthentication.endpoint:type_name -> model.Endpoint
	6, // 3: relay.ClientAuthentication.role:type_name -> model.Role
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
