// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: relay.proto

package pbrelay

import (
	pberror "github.com/connet-dev/connet/proto/pberror"
	pbmodel "github.com/connet-dev/connet/proto/pbmodel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_ChangeUnknown ChangeType = 0
	ChangeType_ChangePut     ChangeType = 1
	ChangeType_ChangeDel     ChangeType = 2
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "ChangeUnknown",
		1: "ChangePut",
		2: "ChangeDel",
	}
	ChangeType_value = map[string]int32{
		"ChangeUnknown": 0,
		"ChangePut":     1,
		"ChangeDel":     2,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

type AuthenticateReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Token             string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Addresses         []*pbmodel.HostPort    `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ReconnectToken    []byte                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	BuildVersion      string                 `protobuf:"bytes,4,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	Metadata          string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ServerCertificate []byte                 `protobuf:"bytes,7,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateReq) GetAddresses() []*pbmodel.HostPort {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *AuthenticateReq) GetReconnectToken() []byte {
	if x != nil {
		return x.ReconnectToken
	}
	return nil
}

func (x *AuthenticateReq) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *AuthenticateReq) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AuthenticateReq) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

type AuthenticateResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Error          *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ControlId      string                 `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	ReconnectToken []byte                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticateResp) Reset() {
	*x = AuthenticateResp{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResp) ProtoMessage() {}

func (x *AuthenticateResp) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResp.ProtoReflect.Descriptor instead.
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResp) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AuthenticateResp) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *AuthenticateResp) GetReconnectToken() []byte {
	if x != nil {
		return x.ReconnectToken
	}
	return nil
}

type ClientsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientsReq) Reset() {
	*x = ClientsReq{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsReq) ProtoMessage() {}

func (x *ClientsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsReq.ProtoReflect.Descriptor instead.
func (*ClientsReq) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ClientsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ClientsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ClientsResp_Change  `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Restart       bool                   `protobuf:"varint,3,opt,name=restart,proto3" json:"restart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientsResp) Reset() {
	*x = ClientsResp{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsResp) ProtoMessage() {}

func (x *ClientsResp) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsResp.ProtoReflect.Descriptor instead.
func (*ClientsResp) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *ClientsResp) GetChanges() []*ClientsResp_Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ClientsResp) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ClientsResp) GetRestart() bool {
	if x != nil {
		return x.Restart
	}
	return false
}

type ServersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersReq) Reset() {
	*x = ServersReq{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersReq) ProtoMessage() {}

func (x *ServersReq) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersReq.ProtoReflect.Descriptor instead.
func (*ServersReq) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *ServersReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ServersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ServersResp_Change  `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Restart       bool                   `protobuf:"varint,3,opt,name=restart,proto3" json:"restart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersResp) Reset() {
	*x = ServersResp{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResp) ProtoMessage() {}

func (x *ServersResp) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResp.ProtoReflect.Descriptor instead.
func (*ServersResp) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *ServersResp) GetChanges() []*ServersResp_Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ServersResp) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ServersResp) GetRestart() bool {
	if x != nil {
		return x.Restart
	}
	return false
}

type ClientsResp_Change struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Change         ChangeType             `protobuf:"varint,1,opt,name=change,proto3,enum=relay.ChangeType" json:"change,omitempty"`
	Endpoint       *pbmodel.Endpoint      `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Role           pbmodel.Role           `protobuf:"varint,3,opt,name=role,proto3,enum=model.Role" json:"role,omitempty"`
	CertificateKey string                 `protobuf:"bytes,4,opt,name=certificate_key,json=certificateKey,proto3" json:"certificate_key,omitempty"`
	Certificate    []byte                 `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientsResp_Change) Reset() {
	*x = ClientsResp_Change{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsResp_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsResp_Change) ProtoMessage() {}

func (x *ClientsResp_Change) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsResp_Change.ProtoReflect.Descriptor instead.
func (*ClientsResp_Change) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ClientsResp_Change) GetChange() ChangeType {
	if x != nil {
		return x.Change
	}
	return ChangeType_ChangeUnknown
}

func (x *ClientsResp_Change) GetEndpoint() *pbmodel.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ClientsResp_Change) GetRole() pbmodel.Role {
	if x != nil {
		return x.Role
	}
	return pbmodel.Role(0)
}

func (x *ClientsResp_Change) GetCertificateKey() string {
	if x != nil {
		return x.CertificateKey
	}
	return ""
}

func (x *ClientsResp_Change) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type ServersResp_Change struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Change            ChangeType             `protobuf:"varint,1,opt,name=change,proto3,enum=relay.ChangeType" json:"change,omitempty"`
	Endpoint          *pbmodel.Endpoint      `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ServerCertificate []byte                 `protobuf:"bytes,3,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServersResp_Change) Reset() {
	*x = ServersResp_Change{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersResp_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResp_Change) ProtoMessage() {}

func (x *ServersResp_Change) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResp_Change.ProtoReflect.Descriptor instead.
func (*ServersResp_Change) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ServersResp_Change) GetChange() ChangeType {
	if x != nil {
		return x.Change
	}
	return ChangeType_ChangeUnknown
}

func (x *ServersResp_Change) GetEndpoint() *pbmodel.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ServersResp_Change) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\x05relay\x1a\verror.proto\x1a\vmodel.proto\"\xef\x01\n" +
	"\x0fAuthenticateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12-\n" +
	"\taddresses\x18\x05 \x03(\v2\x0f.model.HostPortR\taddresses\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\fR\x0ereconnectToken\x12#\n" +
	"\rbuild_version\x18\x04 \x01(\tR\fbuildVersion\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12-\n" +
	"\x12server_certificate\x18\a \x01(\fR\x11serverCertificate\"~\n" +
	"\x10AuthenticateResp\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tR\tcontrolId\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\fR\x0ereconnectToken\"$\n" +
	"\n" +
	"ClientsReq\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"\xc3\x02\n" +
	"\vClientsResp\x123\n" +
	"\achanges\x18\x01 \x03(\v2\x19.relay.ClientsResp.ChangeR\achanges\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x18\n" +
	"\arestart\x18\x03 \x01(\bR\arestart\x1a\xcc\x01\n" +
	"\x06Change\x12)\n" +
	"\x06change\x18\x01 \x01(\x0e2\x11.relay.ChangeTypeR\x06change\x12+\n" +
	"\bendpoint\x18\x02 \x01(\v2\x0f.model.EndpointR\bendpoint\x12\x1f\n" +
	"\x04role\x18\x03 \x01(\x0e2\v.model.RoleR\x04role\x12'\n" +
	"\x0fcertificate_key\x18\x04 \x01(\tR\x0ecertificateKey\x12 \n" +
	"\vcertificate\x18\x05 \x01(\fR\vcertificate\"$\n" +
	"\n" +
	"ServersReq\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"\x86\x02\n" +
	"\vServersResp\x123\n" +
	"\achanges\x18\x01 \x03(\v2\x19.relay.ServersResp.ChangeR\achanges\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x18\n" +
	"\arestart\x18\x03 \x01(\bR\arestart\x1a\x8f\x01\n" +
	"\x06Change\x12)\n" +
	"\x06change\x18\x01 \x01(\x0e2\x11.relay.ChangeTypeR\x06change\x12+\n" +
	"\bendpoint\x18\x02 \x01(\v2\x0f.model.EndpointR\bendpoint\x12-\n" +
	"\x12server_certificate\x18\x03 \x01(\fR\x11serverCertificate*=\n" +
	"\n" +
	"ChangeType\x12\x11\n" +
	"\rChangeUnknown\x10\x00\x12\r\n" +
	"\tChangePut\x10\x01\x12\r\n" +
	"\tChangeDel\x10\x02B,Z*github.com/connet-dev/connet/proto/pbrelayb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_relay_proto_goTypes = []any{
	(ChangeType)(0),            // 0: relay.ChangeType
	(*AuthenticateReq)(nil),    // 1: relay.AuthenticateReq
	(*AuthenticateResp)(nil),   // 2: relay.AuthenticateResp
	(*ClientsReq)(nil),         // 3: relay.ClientsReq
	(*ClientsResp)(nil),        // 4: relay.ClientsResp
	(*ServersReq)(nil),         // 5: relay.ServersReq
	(*ServersResp)(nil),        // 6: relay.ServersResp
	(*ClientsResp_Change)(nil), // 7: relay.ClientsResp.Change
	(*ServersResp_Change)(nil), // 8: relay.ServersResp.Change
	(*pbmodel.HostPort)(nil),   // 9: model.HostPort
	(*pberror.Error)(nil),      // 10: error.Error
	(*pbmodel.Endpoint)(nil),   // 11: model.Endpoint
	(pbmodel.Role)(0),          // 12: model.Role
}
var file_relay_proto_depIdxs = []int32{
	9,  // 0: relay.AuthenticateReq.addresses:type_name -> model.HostPort
	10, // 1: relay.AuthenticateResp.error:type_name -> error.Error
	7,  // 2: relay.ClientsResp.changes:type_name -> relay.ClientsResp.Change
	8,  // 3: relay.ServersResp.changes:type_name -> relay.ServersResp.Change
	0,  // 4: relay.ClientsResp.Change.change:type_name -> relay.ChangeType
	11, // 5: relay.ClientsResp.Change.endpoint:type_name -> model.Endpoint
	12, // 6: relay.ClientsResp.Change.role:type_name -> model.Role
	0,  // 7: relay.ServersResp.Change.change:type_name -> relay.ChangeType
	11, // 8: relay.ServersResp.Change.endpoint:type_name -> model.Endpoint
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
