// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: client_relay.proto

package pbclientrelay

import (
	pberror "github.com/connet-dev/connet/proto/pberror"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BuildVersion  string                 `protobuf:"bytes,3,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_client_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthenticateReq) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

type AuthenticateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResp) Reset() {
	*x = AuthenticateResp{}
	mi := &file_client_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResp) ProtoMessage() {}

func (x *AuthenticateResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResp.ProtoReflect.Descriptor instead.
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResp) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReserveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveReq) Reset() {
	*x = ReserveReq{}
	mi := &file_client_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveReq) ProtoMessage() {}

func (x *ReserveReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveReq.ProtoReflect.Descriptor instead.
func (*ReserveReq) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveReq) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Peer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientCertificate []byte                 `protobuf:"bytes,2,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"` // certificate that peer use to connect to the relay
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_client_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

type ReserveResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Error             *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ServerCertificate []byte                 `protobuf:"bytes,2,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"` // certificate that peers use to connect to the relay
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReserveResp) Reset() {
	*x = ReserveResp{}
	mi := &file_client_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResp) ProtoMessage() {}

func (x *ReserveResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResp.ProtoReflect.Descriptor instead.
func (*ReserveResp) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveResp) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ReserveResp) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

var File_client_relay_proto protoreflect.FileDescriptor

const file_client_relay_proto_rawDesc = "" +
	"\n" +
	"\x12client_relay.proto\x12\fclient_relay\x1a\verror.proto\"S\n" +
	"\x0fAuthenticateReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rbuild_version\x18\x03 \x01(\tR\fbuildVersion\"6\n" +
	"\x10AuthenticateResp\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\"6\n" +
	"\n" +
	"ReserveReq\x12(\n" +
	"\x05peers\x18\x01 \x03(\v2\x12.client_relay.PeerR\x05peers\"E\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x12client_certificate\x18\x02 \x01(\fR\x11clientCertificate\"`\n" +
	"\vReserveResp\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\x12-\n" +
	"\x12server_certificate\x18\x02 \x01(\fR\x11serverCertificateB2Z0github.com/connet-dev/connet/proto/pbclientrelayb\x06proto3"

var (
	file_client_relay_proto_rawDescOnce sync.Once
	file_client_relay_proto_rawDescData []byte
)

func file_client_relay_proto_rawDescGZIP() []byte {
	file_client_relay_proto_rawDescOnce.Do(func() {
		file_client_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_relay_proto_rawDesc), len(file_client_relay_proto_rawDesc)))
	})
	return file_client_relay_proto_rawDescData
}

var file_client_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_client_relay_proto_goTypes = []any{
	(*AuthenticateReq)(nil),  // 0: client_relay.AuthenticateReq
	(*AuthenticateResp)(nil), // 1: client_relay.AuthenticateResp
	(*ReserveReq)(nil),       // 2: client_relay.ReserveReq
	(*Peer)(nil),             // 3: client_relay.Peer
	(*ReserveResp)(nil),      // 4: client_relay.ReserveResp
	(*pberror.Error)(nil),    // 5: error.Error
}
var file_client_relay_proto_depIdxs = []int32{
	5, // 0: client_relay.AuthenticateResp.error:type_name -> error.Error
	3, // 1: client_relay.ReserveReq.peers:type_name -> client_relay.Peer
	5, // 2: client_relay.ReserveResp.error:type_name -> error.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_relay_proto_init() }
func file_client_relay_proto_init() {
	if File_client_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_relay_proto_rawDesc), len(file_client_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_relay_proto_goTypes,
		DependencyIndexes: file_client_relay_proto_depIdxs,
		MessageInfos:      file_client_relay_proto_msgTypes,
	}.Build()
	File_client_relay_proto = out.File
	file_client_relay_proto_goTypes = nil
	file_client_relay_proto_depIdxs = nil
}
