// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: client_relay.proto

package pbclientrelay

import (
	pberror "github.com/connet-dev/connet/proto/pberror"
	pbmodel "github.com/connet-dev/connet/proto/pbmodel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateReq struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Endpoint                *pbmodel.Endpoint      `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Role                    pbmodel.Role           `protobuf:"varint,2,opt,name=role,proto3,enum=model.Role" json:"role,omitempty"`
	AuthenticationSignature []byte                 `protobuf:"bytes,3,opt,name=authentication_signature,json=authenticationSignature,proto3" json:"authentication_signature,omitempty"`
	Metadata                string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	BuildVersion            string                 `protobuf:"bytes,5,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_client_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateReq) GetEndpoint() *pbmodel.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *AuthenticateReq) GetRole() pbmodel.Role {
	if x != nil {
		return x.Role
	}
	return pbmodel.Role(0)
}

func (x *AuthenticateReq) GetAuthenticationSignature() []byte {
	if x != nil {
		return x.AuthenticationSignature
	}
	return nil
}

func (x *AuthenticateReq) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AuthenticateReq) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

type AuthenticateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResp) Reset() {
	*x = AuthenticateResp{}
	mi := &file_client_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResp) ProtoMessage() {}

func (x *AuthenticateResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResp.ProtoReflect.Descriptor instead.
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return file_client_relay_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResp) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_client_relay_proto protoreflect.FileDescriptor

const file_client_relay_proto_rawDesc = "" +
	"\n" +
	"\x12client_relay.proto\x12\fclient_relay\x1a\verror.proto\x1a\vmodel.proto\"\xdb\x01\n" +
	"\x0fAuthenticateReq\x12+\n" +
	"\bendpoint\x18\x01 \x01(\v2\x0f.model.EndpointR\bendpoint\x12\x1f\n" +
	"\x04role\x18\x02 \x01(\x0e2\v.model.RoleR\x04role\x129\n" +
	"\x18authentication_signature\x18\x03 \x01(\fR\x17authenticationSignature\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12#\n" +
	"\rbuild_version\x18\x05 \x01(\tR\fbuildVersion\"6\n" +
	"\x10AuthenticateResp\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05errorB2Z0github.com/connet-dev/connet/proto/pbclientrelayb\x06proto3"

var (
	file_client_relay_proto_rawDescOnce sync.Once
	file_client_relay_proto_rawDescData []byte
)

func file_client_relay_proto_rawDescGZIP() []byte {
	file_client_relay_proto_rawDescOnce.Do(func() {
		file_client_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_relay_proto_rawDesc), len(file_client_relay_proto_rawDesc)))
	})
	return file_client_relay_proto_rawDescData
}

var file_client_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_relay_proto_goTypes = []any{
	(*AuthenticateReq)(nil),  // 0: client_relay.AuthenticateReq
	(*AuthenticateResp)(nil), // 1: client_relay.AuthenticateResp
	(*pbmodel.Endpoint)(nil), // 2: model.Endpoint
	(pbmodel.Role)(0),        // 3: model.Role
	(*pberror.Error)(nil),    // 4: error.Error
}
var file_client_relay_proto_depIdxs = []int32{
	2, // 0: client_relay.AuthenticateReq.endpoint:type_name -> model.Endpoint
	3, // 1: client_relay.AuthenticateReq.role:type_name -> model.Role
	4, // 2: client_relay.AuthenticateResp.error:type_name -> error.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_relay_proto_init() }
func file_client_relay_proto_init() {
	if File_client_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_relay_proto_rawDesc), len(file_client_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_relay_proto_goTypes,
		DependencyIndexes: file_client_relay_proto_depIdxs,
		MessageInfos:      file_client_relay_proto_msgTypes,
	}.Build()
	File_client_relay_proto = out.File
	file_client_relay_proto_goTypes = nil
	file_client_relay_proto_depIdxs = nil
}
