log-level = "debug"

[server]
tokens-file = "examples/token.secret"
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[client]
token-file = "examples/token.secret"
server-cas = ".direnv/localhost/cert.pem"

[client.destinations.sws]
addr = ":8081"

[client.sources.sws]
addr = ":9999"
