log-level = "debug"

[client]
token-file = "examples/client-token.secret"
server-cas = ".direnv/minica.pem"

[client.destinations.sws]
url = "file:."

[client.sources.sws]
url = "tcp://:9999"

[server]
tokens-file = "examples/client-token.secret"
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[control]
clients-tokens-file = "examples/client-token.secret"
relays-tokens-file = "examples/relay-token.secret"

[[control.clients-ingress]]
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[[control.relays-ingress]]
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[relay]
token-file = "examples/relay-token.secret"
control-cas = ".direnv/localhost/cert.pem"
