log-level = "debug"

[server]
tokens-file = "examples/client-token.secret"
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[client]
token-file = "examples/client-token.secret"
server-cas = ".direnv/minica.pem"

[client.destinations.sws-direct]
addr = ":8081"
route = "direct"

[client.sources.sws-direct]
addr = ":9999"
route = "direct"

[client.destinations.sws-relay]
addr = ":8081"
route = "relay"

[client.sources.sws-relay]
addr = ":9998"
route = "relay"
