log-level = "debug"

[server]
tokens-file = "examples/client-token.secret"
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[client]
token-file = "examples/client-token.secret"
server-cas = ".direnv/minica.pem"

[client.destinations.sws-direct]
route = "direct"
http.static-server-root = "."

[client.sources.sws-direct]
route = "direct"
tcp.addr = ":9999"

[client.destinations.sws-relay]
route = "relay"
http.static-server-root = "."

[client.sources.sws-relay]
route = "relay"
tcp.addr = ":9998"
