log-level = "debug"

[server]
tokens-file = "examples/client-token.secret"

[[server.ingress]]
cert-file = ".direnv/localhost/cert.pem"
key-file = ".direnv/localhost/key.pem"

[client]
token-file = "examples/client-token.secret"
server-cas-file = ".direnv/minica.pem"

[client.destinations.sws-direct]
route = "direct"
url = "file:."

[client.sources.sws-direct]
route = "direct"
url = "tcp://:9999"

[client.destinations.sws-relay]
route = "relay"
url = "file:."

[client.sources.sws-relay]
route = "relay"
url = "tcp://:9998"
