// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: connect.proto

package pbconnect

import (
	pberror "github.com/connet-dev/connet/proto/pberror"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyProtoVersion int32

const (
	ProxyProtoVersion_ProxyProtoNone ProxyProtoVersion = 0
	ProxyProtoVersion_V1             ProxyProtoVersion = 1
	ProxyProtoVersion_V2             ProxyProtoVersion = 2
)

// Enum value maps for ProxyProtoVersion.
var (
	ProxyProtoVersion_name = map[int32]string{
		0: "ProxyProtoNone",
		1: "V1",
		2: "V2",
	}
	ProxyProtoVersion_value = map[string]int32{
		"ProxyProtoNone": 0,
		"V1":             1,
		"V2":             2,
	}
)

func (x ProxyProtoVersion) Enum() *ProxyProtoVersion {
	p := new(ProxyProtoVersion)
	*p = x
	return p
}

func (x ProxyProtoVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyProtoVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_proto_enumTypes[0].Descriptor()
}

func (ProxyProtoVersion) Type() protoreflect.EnumType {
	return &file_connect_proto_enumTypes[0]
}

func (x ProxyProtoVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyProtoVersion.Descriptor instead.
func (ProxyProtoVersion) EnumDescriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{0}
}

type RelayEncryptionScheme int32

const (
	RelayEncryptionScheme_EncryptionNone      RelayEncryptionScheme = 0
	RelayEncryptionScheme_TLS                 RelayEncryptionScheme = 1
	RelayEncryptionScheme_DHX25519_CHACHAPOLY RelayEncryptionScheme = 2
)

// Enum value maps for RelayEncryptionScheme.
var (
	RelayEncryptionScheme_name = map[int32]string{
		0: "EncryptionNone",
		1: "TLS",
		2: "DHX25519_CHACHAPOLY",
	}
	RelayEncryptionScheme_value = map[string]int32{
		"EncryptionNone":      0,
		"TLS":                 1,
		"DHX25519_CHACHAPOLY": 2,
	}
)

func (x RelayEncryptionScheme) Enum() *RelayEncryptionScheme {
	p := new(RelayEncryptionScheme)
	*p = x
	return p
}

func (x RelayEncryptionScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayEncryptionScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_proto_enumTypes[1].Descriptor()
}

func (RelayEncryptionScheme) Type() protoreflect.EnumType {
	return &file_connect_proto_enumTypes[1]
}

func (x RelayEncryptionScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayEncryptionScheme.Descriptor instead.
func (RelayEncryptionScheme) EnumDescriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Soft one-of
	Connect       *Request_Connect `protobuf:"bytes,1,opt,name=connect,proto3" json:"connect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetConnect() *Request_Connect {
	if x != nil {
		return x.Connect
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *pberror.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Connect       *Response_Connect      `protobuf:"bytes,2,opt,name=connect,proto3" json:"connect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetError() *pberror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetConnect() *Response_Connect {
	if x != nil {
		return x.Connect
	}
	return nil
}

type TLSConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSConfiguration) Reset() {
	*x = TLSConfiguration{}
	mi := &file_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfiguration) ProtoMessage() {}

func (x *TLSConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfiguration.ProtoReflect.Descriptor instead.
func (*TLSConfiguration) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{2}
}

func (x *TLSConfiguration) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type ECDHConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	KeyTime       []byte                 `protobuf:"bytes,2,opt,name=key_time,json=keyTime,proto3" json:"key_time,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDHConfiguration) Reset() {
	*x = ECDHConfiguration{}
	mi := &file_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDHConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDHConfiguration) ProtoMessage() {}

func (x *ECDHConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDHConfiguration.ProtoReflect.Descriptor instead.
func (*ECDHConfiguration) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{3}
}

func (x *ECDHConfiguration) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ECDHConfiguration) GetKeyTime() []byte {
	if x != nil {
		return x.KeyTime
	}
	return nil
}

func (x *ECDHConfiguration) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Request_Connect struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	SourceEncryption []RelayEncryptionScheme `protobuf:"varint,1,rep,packed,name=source_encryption,json=sourceEncryption,proto3,enum=connect.RelayEncryptionScheme" json:"source_encryption,omitempty"`
	SourceTls        *TLSConfiguration       `protobuf:"bytes,2,opt,name=source_tls,json=sourceTls,proto3" json:"source_tls,omitempty"`
	SourceDhX25519   *ECDHConfiguration      `protobuf:"bytes,3,opt,name=source_dh_x25519,json=sourceDhX25519,proto3" json:"source_dh_x25519,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Request_Connect) Reset() {
	*x = Request_Connect{}
	mi := &file_connect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Connect) ProtoMessage() {}

func (x *Request_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Connect.ProtoReflect.Descriptor instead.
func (*Request_Connect) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_Connect) GetSourceEncryption() []RelayEncryptionScheme {
	if x != nil {
		return x.SourceEncryption
	}
	return nil
}

func (x *Request_Connect) GetSourceTls() *TLSConfiguration {
	if x != nil {
		return x.SourceTls
	}
	return nil
}

func (x *Request_Connect) GetSourceDhX25519() *ECDHConfiguration {
	if x != nil {
		return x.SourceDhX25519
	}
	return nil
}

type Response_Connect struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProxyProto            ProxyProtoVersion      `protobuf:"varint,1,opt,name=proxy_proto,json=proxyProto,proto3,enum=connect.ProxyProtoVersion" json:"proxy_proto,omitempty"`
	DestinationEncryption RelayEncryptionScheme  `protobuf:"varint,2,opt,name=destination_encryption,json=destinationEncryption,proto3,enum=connect.RelayEncryptionScheme" json:"destination_encryption,omitempty"`
	DestinationTls        *TLSConfiguration      `protobuf:"bytes,3,opt,name=destination_tls,json=destinationTls,proto3" json:"destination_tls,omitempty"`
	DestinationDhX25519   *ECDHConfiguration     `protobuf:"bytes,4,opt,name=destination_dh_x25519,json=destinationDhX25519,proto3" json:"destination_dh_x25519,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Response_Connect) Reset() {
	*x = Response_Connect{}
	mi := &file_connect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Connect) ProtoMessage() {}

func (x *Response_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Connect.ProtoReflect.Descriptor instead.
func (*Response_Connect) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_Connect) GetProxyProto() ProxyProtoVersion {
	if x != nil {
		return x.ProxyProto
	}
	return ProxyProtoVersion_ProxyProtoNone
}

func (x *Response_Connect) GetDestinationEncryption() RelayEncryptionScheme {
	if x != nil {
		return x.DestinationEncryption
	}
	return RelayEncryptionScheme_EncryptionNone
}

func (x *Response_Connect) GetDestinationTls() *TLSConfiguration {
	if x != nil {
		return x.DestinationTls
	}
	return nil
}

func (x *Response_Connect) GetDestinationDhX25519() *ECDHConfiguration {
	if x != nil {
		return x.DestinationDhX25519
	}
	return nil
}

var File_connect_proto protoreflect.FileDescriptor

const file_connect_proto_rawDesc = "" +
	"\n" +
	"\rconnect.proto\x12\aconnect\x1a\verror.proto\"\x96\x02\n" +
	"\aRequest\x122\n" +
	"\aconnect\x18\x01 \x01(\v2\x18.connect.Request.ConnectR\aconnect\x1a\xd6\x01\n" +
	"\aConnect\x12K\n" +
	"\x11source_encryption\x18\x01 \x03(\x0e2\x1e.connect.RelayEncryptionSchemeR\x10sourceEncryption\x128\n" +
	"\n" +
	"source_tls\x18\x02 \x01(\v2\x19.connect.TLSConfigurationR\tsourceTls\x12D\n" +
	"\x10source_dh_x25519\x18\x03 \x01(\v2\x1a.connect.ECDHConfigurationR\x0esourceDhX25519\"\x97\x03\n" +
	"\bResponse\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorR\x05error\x123\n" +
	"\aconnect\x18\x02 \x01(\v2\x19.connect.Response.ConnectR\aconnect\x1a\xb1\x02\n" +
	"\aConnect\x12;\n" +
	"\vproxy_proto\x18\x01 \x01(\x0e2\x1a.connect.ProxyProtoVersionR\n" +
	"proxyProto\x12U\n" +
	"\x16destination_encryption\x18\x02 \x01(\x0e2\x1e.connect.RelayEncryptionSchemeR\x15destinationEncryption\x12B\n" +
	"\x0fdestination_tls\x18\x03 \x01(\v2\x19.connect.TLSConfigurationR\x0edestinationTls\x12N\n" +
	"\x15destination_dh_x25519\x18\x04 \x01(\v2\x1a.connect.ECDHConfigurationR\x13destinationDhX25519\"3\n" +
	"\x10TLSConfiguration\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\"m\n" +
	"\x11ECDHConfiguration\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12\x19\n" +
	"\bkey_time\x18\x02 \x01(\fR\akeyTime\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature*7\n" +
	"\x11ProxyProtoVersion\x12\x12\n" +
	"\x0eProxyProtoNone\x10\x00\x12\x06\n" +
	"\x02V1\x10\x01\x12\x06\n" +
	"\x02V2\x10\x02*M\n" +
	"\x15RelayEncryptionScheme\x12\x12\n" +
	"\x0eEncryptionNone\x10\x00\x12\a\n" +
	"\x03TLS\x10\x01\x12\x17\n" +
	"\x13DHX25519_CHACHAPOLY\x10\x02B.Z,github.com/connet-dev/connet/proto/pbconnectb\x06proto3"

var (
	file_connect_proto_rawDescOnce sync.Once
	file_connect_proto_rawDescData []byte
)

func file_connect_proto_rawDescGZIP() []byte {
	file_connect_proto_rawDescOnce.Do(func() {
		file_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)))
	})
	return file_connect_proto_rawDescData
}

var file_connect_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_connect_proto_goTypes = []any{
	(ProxyProtoVersion)(0),     // 0: connect.ProxyProtoVersion
	(RelayEncryptionScheme)(0), // 1: connect.RelayEncryptionScheme
	(*Request)(nil),            // 2: connect.Request
	(*Response)(nil),           // 3: connect.Response
	(*TLSConfiguration)(nil),   // 4: connect.TLSConfiguration
	(*ECDHConfiguration)(nil),  // 5: connect.ECDHConfiguration
	(*Request_Connect)(nil),    // 6: connect.Request.Connect
	(*Response_Connect)(nil),   // 7: connect.Response.Connect
	(*pberror.Error)(nil),      // 8: error.Error
}
var file_connect_proto_depIdxs = []int32{
	6,  // 0: connect.Request.connect:type_name -> connect.Request.Connect
	8,  // 1: connect.Response.error:type_name -> error.Error
	7,  // 2: connect.Response.connect:type_name -> connect.Response.Connect
	1,  // 3: connect.Request.Connect.source_encryption:type_name -> connect.RelayEncryptionScheme
	4,  // 4: connect.Request.Connect.source_tls:type_name -> connect.TLSConfiguration
	5,  // 5: connect.Request.Connect.source_dh_x25519:type_name -> connect.ECDHConfiguration
	0,  // 6: connect.Response.Connect.proxy_proto:type_name -> connect.ProxyProtoVersion
	1,  // 7: connect.Response.Connect.destination_encryption:type_name -> connect.RelayEncryptionScheme
	4,  // 8: connect.Response.Connect.destination_tls:type_name -> connect.TLSConfiguration
	5,  // 9: connect.Response.Connect.destination_dh_x25519:type_name -> connect.ECDHConfiguration
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_connect_proto_init() }
func file_connect_proto_init() {
	if File_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_proto_goTypes,
		DependencyIndexes: file_connect_proto_depIdxs,
		EnumInfos:         file_connect_proto_enumTypes,
		MessageInfos:      file_connect_proto_msgTypes,
	}.Build()
	File_connect_proto = out.File
	file_connect_proto_goTypes = nil
	file_connect_proto_depIdxs = nil
}
