// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: relay.proto

package pbr

import (
	pb "github.com/keihaya-com/connet/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayChange int32

const (
	RelayChange_ChangeUnknown RelayChange = 0
	RelayChange_ChangePut     RelayChange = 1
	RelayChange_ChangeDel     RelayChange = 2
)

// Enum value maps for RelayChange.
var (
	RelayChange_name = map[int32]string{
		0: "ChangeUnknown",
		1: "ChangePut",
		2: "ChangeDel",
	}
	RelayChange_value = map[string]int32{
		"ChangeUnknown": 0,
		"ChangePut":     1,
		"ChangeDel":     2,
	}
)

func (x RelayChange) Enum() *RelayChange {
	p := new(RelayChange)
	*p = x
	return p
}

func (x RelayChange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayChange) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (RelayChange) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x RelayChange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayChange.Descriptor instead.
func (RelayChange) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

type RelayAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Addr  *pb.HostPort `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *RelayAuth) Reset() {
	*x = RelayAuth{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAuth) ProtoMessage() {}

func (x *RelayAuth) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAuth.ProtoReflect.Descriptor instead.
func (*RelayAuth) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RelayAuth) GetAddr() *pb.HostPort {
	if x != nil {
		return x.Addr
	}
	return nil
}

type RelayAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     *pb.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ControlId string    `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
}

func (x *RelayAuthResp) Reset() {
	*x = RelayAuthResp{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAuthResp) ProtoMessage() {}

func (x *RelayAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAuthResp.ProtoReflect.Descriptor instead.
func (*RelayAuthResp) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RelayAuthResp) GetError() *pb.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RelayAuthResp) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

type RelayClientsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *RelayClientsReq) Reset() {
	*x = RelayClientsReq{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayClientsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayClientsReq) ProtoMessage() {}

func (x *RelayClientsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayClientsReq.ProtoReflect.Descriptor instead.
func (*RelayClientsReq) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *RelayClientsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RelayClients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changes []*RelayClients_Change `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Offset  int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Restart bool                   `protobuf:"varint,3,opt,name=restart,proto3" json:"restart,omitempty"`
}

func (x *RelayClients) Reset() {
	*x = RelayClients{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayClients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayClients) ProtoMessage() {}

func (x *RelayClients) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayClients.ProtoReflect.Descriptor instead.
func (*RelayClients) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RelayClients) GetChanges() []*RelayClients_Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *RelayClients) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RelayClients) GetRestart() bool {
	if x != nil {
		return x.Restart
	}
	return false
}

type RelayServersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *RelayServersReq) Reset() {
	*x = RelayServersReq{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayServersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayServersReq) ProtoMessage() {}

func (x *RelayServersReq) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayServersReq.ProtoReflect.Descriptor instead.
func (*RelayServersReq) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RelayServersReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RelayServers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changes []*RelayServers_Change `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Offset  int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Restart bool                   `protobuf:"varint,3,opt,name=restart,proto3" json:"restart,omitempty"`
}

func (x *RelayServers) Reset() {
	*x = RelayServers{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayServers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayServers) ProtoMessage() {}

func (x *RelayServers) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayServers.ProtoReflect.Descriptor instead.
func (*RelayServers) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *RelayServers) GetChanges() []*RelayServers_Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *RelayServers) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RelayServers) GetRestart() bool {
	if x != nil {
		return x.Restart
	}
	return false
}

type RelayClients_Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination       *pb.Forward `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Source            *pb.Forward `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ClientCertificate []byte      `protobuf:"bytes,3,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	Change            RelayChange `protobuf:"varint,4,opt,name=change,proto3,enum=relay.RelayChange" json:"change,omitempty"`
}

func (x *RelayClients_Change) Reset() {
	*x = RelayClients_Change{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayClients_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayClients_Change) ProtoMessage() {}

func (x *RelayClients_Change) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayClients_Change.ProtoReflect.Descriptor instead.
func (*RelayClients_Change) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RelayClients_Change) GetDestination() *pb.Forward {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *RelayClients_Change) GetSource() *pb.Forward {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RelayClients_Change) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

func (x *RelayClients_Change) GetChange() RelayChange {
	if x != nil {
		return x.Change
	}
	return RelayChange_ChangeUnknown
}

type RelayServers_Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server            *pb.Forward `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ServerCertificate []byte      `protobuf:"bytes,2,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	Change            RelayChange `protobuf:"varint,3,opt,name=change,proto3,enum=relay.RelayChange" json:"change,omitempty"`
}

func (x *RelayServers_Change) Reset() {
	*x = RelayServers_Change{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayServers_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayServers_Change) ProtoMessage() {}

func (x *RelayServers_Change) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayServers_Change.ProtoReflect.Descriptor instead.
func (*RelayServers_Change) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RelayServers_Change) GetServer() *pb.Forward {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *RelayServers_Change) GetServerCertificate() []byte {
	if x != nil {
		return x.ServerCertificate
	}
	return nil
}

func (x *RelayServers_Change) GetChange() RelayChange {
	if x != nil {
		return x.Change
	}
	return RelayChange_ChangeUnknown
}

var File_relay_proto protoreflect.FileDescriptor

var file_relay_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72,
	0x65, 0x6c, 0x61, 0x79, 0x1a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x47, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x53, 0x0a, 0x0d, 0x52,
	0x65, 0x6c, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x64,
	0x22, 0x29, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xb8, 0x02, 0x0a, 0x0c,
	0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x1a, 0xbf, 0x01, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x31, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x85, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x8c, 0x01, 0x0a, 0x06, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2d,
	0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2a, 0x3e, 0x0a, 0x0b, 0x52, 0x65, 0x6c,
	0x61, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x75, 0x74, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x10, 0x02, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x69, 0x68, 0x61, 0x79, 0x61, 0x2d,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData = file_relay_proto_rawDesc
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(file_relay_proto_rawDescData)
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_relay_proto_goTypes = []any{
	(RelayChange)(0),            // 0: relay.RelayChange
	(*RelayAuth)(nil),           // 1: relay.RelayAuth
	(*RelayAuthResp)(nil),       // 2: relay.RelayAuthResp
	(*RelayClientsReq)(nil),     // 3: relay.RelayClientsReq
	(*RelayClients)(nil),        // 4: relay.RelayClients
	(*RelayServersReq)(nil),     // 5: relay.RelayServersReq
	(*RelayServers)(nil),        // 6: relay.RelayServers
	(*RelayClients_Change)(nil), // 7: relay.RelayClients.Change
	(*RelayServers_Change)(nil), // 8: relay.RelayServers.Change
	(*pb.HostPort)(nil),         // 9: shared.HostPort
	(*pb.Error)(nil),            // 10: shared.Error
	(*pb.Forward)(nil),          // 11: shared.Forward
}
var file_relay_proto_depIdxs = []int32{
	9,  // 0: relay.RelayAuth.addr:type_name -> shared.HostPort
	10, // 1: relay.RelayAuthResp.error:type_name -> shared.Error
	7,  // 2: relay.RelayClients.changes:type_name -> relay.RelayClients.Change
	8,  // 3: relay.RelayServers.changes:type_name -> relay.RelayServers.Change
	11, // 4: relay.RelayClients.Change.destination:type_name -> shared.Forward
	11, // 5: relay.RelayClients.Change.source:type_name -> shared.Forward
	0,  // 6: relay.RelayClients.Change.change:type_name -> relay.RelayChange
	11, // 7: relay.RelayServers.Change.server:type_name -> shared.Forward
	0,  // 8: relay.RelayServers.Change.change:type_name -> relay.RelayChange
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relay_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_rawDesc = nil
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
