// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: error.proto

package pberror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	// Generic
	Code_Unknown               Code = 0
	Code_RequestUnknown        Code = 1
	Code_ConnectionCheckFailed Code = 2
	// Authentication
	Code_AuthenticationFailed Code = 100
	Code_EndpointNotAllowed   Code = 101
	Code_RoleNotAllowed       Code = 102
	// Announce
	Code_AnnounceValidationFailed         Code = 200
	Code_AnnounceInvalidClientCertificate Code = 201
	Code_AnnounceInvalidServerCertificate Code = 202
	// Relay
	Code_RelayValidationFailed   Code = 300
	Code_RelayInvalidCertificate Code = 301
	Code_RelayKeepaliveClosed    Code = 302
	// Direct
	Code_DirectConnectionClosed Code = 400
	Code_DirectKeepaliveClosed  Code = 401
	// Client connect codes
	Code_DestinationNotFound             Code = 500
	Code_DestinationDialFailed           Code = 501
	Code_DestinationRelayEncryptionError Code = 502
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:   "Unknown",
		1:   "RequestUnknown",
		2:   "ConnectionCheckFailed",
		100: "AuthenticationFailed",
		101: "EndpointNotAllowed",
		102: "RoleNotAllowed",
		200: "AnnounceValidationFailed",
		201: "AnnounceInvalidClientCertificate",
		202: "AnnounceInvalidServerCertificate",
		300: "RelayValidationFailed",
		301: "RelayInvalidCertificate",
		302: "RelayKeepaliveClosed",
		400: "DirectConnectionClosed",
		401: "DirectKeepaliveClosed",
		500: "DestinationNotFound",
		501: "DestinationDialFailed",
		502: "DestinationRelayEncryptionError",
	}
	Code_value = map[string]int32{
		"Unknown":                          0,
		"RequestUnknown":                   1,
		"ConnectionCheckFailed":            2,
		"AuthenticationFailed":             100,
		"EndpointNotAllowed":               101,
		"RoleNotAllowed":                   102,
		"AnnounceValidationFailed":         200,
		"AnnounceInvalidClientCertificate": 201,
		"AnnounceInvalidServerCertificate": 202,
		"RelayValidationFailed":            300,
		"RelayInvalidCertificate":          301,
		"RelayKeepaliveClosed":             302,
		"DirectConnectionClosed":           400,
		"DirectKeepaliveClosed":            401,
		"DestinationNotFound":              500,
		"DestinationDialFailed":            501,
		"DestinationRelayEncryptionError":  502,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=error.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Unknown
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\x05error\"B\n" +
	"\x05Error\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.error.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xdf\x03\n" +
	"\x04Code\x12\v\n" +
	"\aUnknown\x10\x00\x12\x12\n" +
	"\x0eRequestUnknown\x10\x01\x12\x19\n" +
	"\x15ConnectionCheckFailed\x10\x02\x12\x18\n" +
	"\x14AuthenticationFailed\x10d\x12\x16\n" +
	"\x12EndpointNotAllowed\x10e\x12\x12\n" +
	"\x0eRoleNotAllowed\x10f\x12\x1d\n" +
	"\x18AnnounceValidationFailed\x10\xc8\x01\x12%\n" +
	" AnnounceInvalidClientCertificate\x10\xc9\x01\x12%\n" +
	" AnnounceInvalidServerCertificate\x10\xca\x01\x12\x1a\n" +
	"\x15RelayValidationFailed\x10\xac\x02\x12\x1c\n" +
	"\x17RelayInvalidCertificate\x10\xad\x02\x12\x19\n" +
	"\x14RelayKeepaliveClosed\x10\xae\x02\x12\x1b\n" +
	"\x16DirectConnectionClosed\x10\x90\x03\x12\x1a\n" +
	"\x15DirectKeepaliveClosed\x10\x91\x03\x12\x18\n" +
	"\x13DestinationNotFound\x10\xf4\x03\x12\x1a\n" +
	"\x15DestinationDialFailed\x10\xf5\x03\x12$\n" +
	"\x1fDestinationRelayEncryptionError\x10\xf6\x03B,Z*github.com/connet-dev/connet/proto/pberrorb\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_error_proto_goTypes = []any{
	(Code)(0),     // 0: error.Code
	(*Error)(nil), // 1: error.Error
}
var file_error_proto_depIdxs = []int32{
	0, // 0: error.Error.code:type_name -> error.Code
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
