on:
  pull_request:
  push:
    branches: [main]

jobs:
  go-build:
    name: Build and check golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: HatsuneMiku3939/direnv-action@v1
      - name: direnv allow
        run: direnv allow .
      - name: go mod tidy
        run: direnv exec . go mod tidy
      - name: exit if not tidy
        run: |
          git diff --exit-code go.mod
          git diff --exit-code go.sum
      - name: Build
        run: direnv exec . go build -v ./...
      - name: Test
        run: direnv exec . go test -v ./...
    
  nix-build:
    name: Build nix package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build .
