on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  docker-build-x86:
    name: Build x86 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Docker build
        run: nix build .#docker
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: nix develop --command skopeo copy "docker-archive:result" "docker://ghcr.io/connet-dev/connet:latest-amd64"

  docker-build-arm:
    name: Build arm image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: system = aarch64-linux
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Docker build
        run: nix build .#docker
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: nix develop --command skopeo copy "docker-archive:result" "docker://ghcr.io/connet-dev/connet:latest-arm64"

  docker-multiarch:
    name: Tag multi-arch
    runs-on: ubuntu-latest
    needs: [docker-build-x86, docker-build-arm]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker tag
        run: nix develop --command manifest-tool push from-args --platforms linux/amd64,linux/arm64 --template ghcr.io/connet-dev/connet:latest-ARCHVARIANT --target ghcr.io/connet-dev/connet:latest
    
